/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as ProveedoresRouteImport } from './routes/proveedores'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as VentasRouteImport } from './routes/ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProveedoresRoute = ProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/productos': typeof ProductosRoute
  '/proveedores': typeof ProveedoresRoute
  '/reportes': typeof ReportesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/productos' | '/proveedores' | '/reportes' | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/productos' | '/proveedores' | '/reportes' | '/ventas'
  id: '__root__' | '/' | '/productos' | '/proveedores' | '/reportes' | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductosRoute: typeof ProductosRoute
  ProveedoresRoute: typeof ProveedoresRoute
  ReportesRoute: typeof ReportesRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proveedores': {
      id: '/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof ProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductosRoute: ProductosRoute,
  ProveedoresRoute: ProveedoresRoute,
  ReportesRoute: ReportesRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
